# Конфигурация сервера, используйте если хотите сделать сервер общим.

enableConfig: 0 # Для включения конфига измените значение на 1

maxClients: 5 # Сколько клиентов может подключиться к серверу?

maxBotsPerClient: 100 # Сколько максимум ботов может подключить один клиент?
maxBotsConnecting: 1000 # Сколько может быть максимум подключающихся ботов на один клиент?

connectMaxBots: 300 # Сколько ботов можно подключить за раз?
connectMinDelay: 2 # Минимальная задержка подключения ботов (мс)
multipleConnects: false # Несколько команд подключения за раз

commandTimeout: 1 # Задержка между командами (сек)

allAdmins: false # Делать ли всех админами?
admins: # Список админов, админы могут использовать опасные команды по типу .bots rserver а также игнорировать все ограничения.
    - "JustNanix"
